language: c

os:
  - linux

sudo: required

services:
  - docker

env:
  global:
    - ENCRYPTION_LABEL: "9fdce5882088"
    - COMMIT_AUTHOR_EMAIL: "kai@kzhang.org"
  matrix:
    - BUILD: "docs"
    - BUILD: "exe"

python:
  - "3.5"

#deploy:
#  provider: releases
#  api_key:
#  file: ".stack-work/"
#  skip_cleanup: true
#  on:
#    tags: true

before_install:
  - if [ "$BUILD" == "exe" ]; then docker pull kaizhang/haskell-stack; fi
  - if [ "$BUILD" == "docs" ]; then pip install sphinx==1.5.6 sphinxcontrib-versioning sphinx_rtd_theme; fi

script:
  - if [ "$BUILD" == "exe" ]; then bash build.sh; fi
  - if [ "$BUILD" == "docs" ]; then bash mkdoc.sh; fi
