language: c

os:
  - linux

sudo: required

services:
  - docker

env:
  global:
    - ENCRYPTION_LABEL: "9fdce5882088"
    - COMMIT_AUTHOR_EMAIL: "kai@kzhang.org"
    - BUILD: "docs"
    - BUILD: "exe"

python:
  - "3.5"

before_install:
  - if [ "$BUILD" == "exe" ]; then docker pull kaizhang/haskell-stack; fi
  - if [ "$BUILD" == "docs" ]; then pip install sphinx==1.5.6 sphinxcontrib-versioning sphinx_rtd_theme; fi

script:
  - if [ "$BUILD" == "exe" ]; then docker run -v `pwd`:/build:rw kaizhang/haskell-stack /bin/bash -c "cd build && stack build --allow-different-user"; fi
  - if [ "$BUILD" == "docs" ]; then bash docs/deploy.sh; fi
