language: c

os:
  - linux

sudo: required

services:
  - docker

env:
  - TARGET=docs
  - TARGET=exe

python:
  - "3.5"

before_install:
  - if [ "$TARGET" == "exe" ]; then docker pull kaizhang/haskell-stack; fi
  - if [ "$TARGET" == "docs" ]; then pip install sphinx==1.5.6 sphinxcontrib-versioning sphinx_rtd_theme; fi

script:
  - if [ "$TARGET" == "exe" ]; then docker run -v `pwd`:/build:rw kaizhang/haskell-stack /bin/bash -c "cd build && stack build --allow-different-user"; fi
  - if [ "$TARGET" == "docs" ]; then sphinx-versioning push -r master docs gh-pages .; fi
