language: c

os:
  - linux

sudo: required

services:
  - docker

env:
  - PATH=$HOME/.local/bin:$PATH

before_install:
  - docker pull kaizhang/haskell-stack

script:
  - docker run -v `pwd`:/build:rw kaizhang/haskell-stack /bin/bash -c "cd build && stack build --allow-different-user"
