################################################################################
# NOTE: Lines starting with a '#' character are comments.
################################################################################

# The path to a file specifying the input data sets. The software come with
# an example file named "input.yaml".
input: "data/input.yml"

# Directory containing the results.
outputDir: "output/"

# The path to the picard tools.
picard: "/home/kai/software/picard-tools-1.140/picard.jar"


################################################################################
# Genome Indices
################################################################################

# Complete genome in a SINGLE plain FASTA file. Genomes can be downloaded from
# http://hgdownload.cse.ucsc.edu/downloads.html. For example, this link gives
# you the complete human genome:
# http://hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/hg38.fa.gz
# Important: Remember to ungzip the file using "gzip -d hg38.fa.gz"!
# Tip: To make a single genome file from multiple fastq files, execute:
# `cat chr1.fa chr2.fa chr3.fa > genome.fa`
genome: "/home/kai/genome/GRCh38/genome.fa"

# Genome annotation in *GTF* format. For human and mouse, Gencode annotations are
# available at http://www.gencodegenes.org/
annotation: "/home/kai/genome/GRCh38/Annotation/gencode.v25.annotation.gtf"

# MEME format file containing motifs. Human and mouse motif files can be
# here: https://github.com/kaizhang/Taiji/tree/master/data/motifs
motifFile: "/home/kai/motif_databases/cisBP_human.meme"


################################################################################
# You don't have to physically provide the following files. But you do need to
# specify the locations where these files will be generated AUTOMATICALLY IF
# they are absent. Note the program DO NOT overwrite existing files/directories
# so that these files can be reused between different runs.
# If you want to re-generate indices, make sure delete correponding
# files/directories first.
################################################################################

# Genome sequence index.
seqIndex: "/home/kai/genome/GRCh38/GRCh38.index"

# Directory containing the BWA indices.
bwaIndex: "/home/kai/genome/GRCh38/BWAIndex/"

# Uncomment following sections if you want to analyze raw RNA-seq fastq files.
# NOTE: STAR aligner uses a lot memory.
# For example, you need at least 30G memory for human genome.

# Directory containing the STAR indices.
# starIndex: "/home/kai/genome/GRCh38/STAR_index/"

# Directory containing the RSEM indices
# rsemIndex: "/home/kai/genome/GRCh38/RSEM_index/"
