resolver: lts-7.8

packages:
    - '.'

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: d4e83a4b1899454694df408ed37fe639409ed018

    - location:
        git: https://github.com/kaizhang/bio-pipelines.git
        commit: fd02dacde9020935e965d6694f6c9fd35d05c919

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: 3b92159a7cd8ad9973e17c22d4f8f8fcf575b054

extra-deps:
#    - SciFlow-0.5.3.1
    - bioinformatics-toolkit-0.3.1
    - haskell-igraph-0.2.2
    - hexpat-0.20.9
    - List-0.5.2
    - drmaa-0.1.1
    - HsHTSLib-1.3.2.0
