resolver: lts-7.3

packages:
    - '.'

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: 97f967fc6821dc37349bffb7e97c3187584e229a

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: 0c95802cf2f6b7974441c7e2401566180f0030ac

    - location:
        git: https://github.com/kaizhang/haskell-igraph.git
        commit: 670c670d7165c545b12d2db663ec7fc23966385a

    - location:
        git: https://github.com/kaizhang/bio-pipelines.git
        commit: baa7e272f819d79b4ad0317c944ea61d9942ad4e

extra-deps:
    - samtools-0.2.4.3
    - bioinformatics-toolkit-0.2.3
    - hexpat-0.20.9
    - List-0.5.2

# Uncomment following lines if you want to use SGE
    - drmaa-0.1.0.1

flags:
    SciFlow:
        sge: true
