resolver: lts-6.10

packages:
- '.'

- location:
    git: https://github.com/kaizhang/SciFlow.git
    commit: fdd59558a980e52dafafefe295cd1d07d2395dd2

- location:
    git: https://github.com/kaizhang/bio-experiments.git
    commit: f45d73d38395bf5a51b50e893ccbcf39b3c97f2a

- location:
    git: https://github.com/kaizhang/bio-pipelines.git
    commit: 5d0ee26315f6908607d5fbd960a0ff728b5d5e9b

- location:
    git: git@github.com:kaizhang/bioinformatics-toolkit.git
    commit: d52ffdca7daf8f9424b01b470d0cbfc35723506d

extra-deps:
    - samtools-0.2.4.3
    - haskell-igraph-0.1.0
    - drmaa-0.1.0.1

flags:
    SciFlow:
        debug: true
        sge: true
