resolver: lts-8.8

packages:
    - 'taiji'
    - 'taiji-viz'
    - 'bio-pipelines'

    - location:
        git: https://github.com/kaizhang/bioinformatics-toolkit.git
        commit: 8d215c97a74eeab264effcd3b8c351d510e6f0c2

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: 3d268c3b0cf0006b5c5ad01240b62ddbeb349bc0

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: a623a91c9829208c2d98d69e77827f7e975e7136

extra-deps:
    - haskell-igraph-0.3.0
    - drmaa-0.2.0
    - HsHTSLib-1.3.2.0
