resolver: lts-8.5

packages:
    - 'taiji'
    - 'taiji-viz'
    - 'bio-pipelines'

    - location:
        git: https://github.com/kaizhang/bioinformatics-toolkit.git
        commit: 8d215c97a74eeab264effcd3b8c351d510e6f0c2

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: 3d268c3b0cf0006b5c5ad01240b62ddbeb349bc0

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: bc0abe9d709692217bf6a31593646dad7e310aba

extra-deps:
    - haskell-igraph-0.2.2
    - hexpat-0.20.9
    - List-0.5.2
    - drmaa-0.2.0
    - HsHTSLib-1.3.2.0
