resolver: nightly-2017-06-23

packages:
    - 'Taiji'
    - 'Taiji-viz'
    - 'bio-pipelines'
    - 'bio-experiments'

    - location:
        git: https://github.com/kaizhang/bioinformatics-toolkit.git
        commit: 8d215c97a74eeab264effcd3b8c351d510e6f0c2

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: 81e0649f83f56257654d0ddb2602837549b5fc89

extra-deps:
    - haskell-igraph-0.3.0
    - drmaa-0.2.0
    - HsHTSLib-1.3.2.0
