resolver: lts-7.0

packages:
    - '.'

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: 82c309a60898cc0292fbf4d8802956e4ffebf2de

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: e125b18adde156d82e48ec57615c4992b724a3f0

    - location:
        git: https://github.com/kaizhang/haskell-igraph.git
        commit: 4622414876481fdb45db9db185745fa8a5ba50fa

    - location:
        git: https://github.com/kaizhang/bio-pipelines.git
        commit: 3242aa63d40152218fb48f9f3dea659eb33d14e7

extra-deps:
    - samtools-0.2.4.3
    - bioinformatics-toolkit-0.2.2
    - hexpat-0.20.9
    - List-0.5.2

# Uncomment following lines if you want to use SGE
#    - drmaa-0.1.0.1

#flags:
#    SciFlow:
#        sge: true
