resolver: nightly-2016-12-06

packages:
    - 'taiji'

    - 'taiji-viz'

    - location:
        git: https://github.com/kaizhang/bioinformatics-toolkit.git
        commit: 5a488832a6c6b66f5a97f85b07babb319648a2b0

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: 3d268c3b0cf0006b5c5ad01240b62ddbeb349bc0

    - location:
        git: https://github.com/kaizhang/bio-pipelines.git
        commit: 4339f3dffa58498077e9a6a06e191d6bee8f7751

    - location:
        git: https://github.com/kaizhang/SciFlow.git
        commit: 47d01ab509075c83159c8b9764253546c10754be

extra-deps:
    - haskell-igraph-0.2.2
    - hexpat-0.20.9
    - List-0.5.2
    - drmaa-0.1.1
    - HsHTSLib-1.3.2.0
