resolver: lts-7.3

packages:
    - '.'
    - '../bio-pipelines'
    - '../SciFlow'

    #- location:
    #    git: https://github.com/kaizhang/SciFlow.git
    #    commit: e6fec402b8746ee02b9b7f057a4d8e8e7ef530cf

    - location:
        git: https://github.com/kaizhang/bio-experiments.git
        commit: 0c95802cf2f6b7974441c7e2401566180f0030ac

    - location:
        git: https://github.com/kaizhang/haskell-igraph.git
        commit: 670c670d7165c545b12d2db663ec7fc23966385a

    #- location:
    #    git: https://github.com/kaizhang/bio-pipelines.git
    #    commit: 3242aa63d40152218fb48f9f3dea659eb33d14e7

extra-deps:
    - samtools-0.2.4.3
    - bioinformatics-toolkit-0.2.3
    - hexpat-0.20.9
    - List-0.5.2

# Uncomment following lines if you want to use SGE
    - drmaa-0.1.0.1

flags:
    SciFlow:
        sge: true
